### ISSUE TITLE
WDB extracts only DLL files that are exactly 160 KB in size.

### ISSUE THREAD

**Issue by KidGbzin** [michaelwright235/wdb_extract#1]
Hello Michael! ✨

I found that the decryptor fails if the `Inf_WebDnld.dll` file size differs from 160 KB.

![Captura de tela 2024-09-01 161909](https://github.com/user-attachments/assets/215bb5e0-488d-4710-83cb-7e7a32237d96)

The script works perfectly on the KP500 (160 KB), GS290 (160 KB), and KS360 (160 KB). However, it fails when attempting to process firmware versions with different DLL sizes, such as the KP275 (152 KB) or GT350 (172 KB).

Is there any chance to add support for decrypting files with sizes other than 160 KB?

Thank you in advance for creating such a fantastic tool.

**Comment by michaelwright235** [comment]
Hi!
Thanks for posting this issue, I'd be great to add support for other LG models. I'll look into it in my spare time, but probably it'll need some extra reverse engineering stuff.

**Comment by michaelwright235** [comment]
Fixed with a8e7829.
